on:
  push:
    tags:
      - 'v*'

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "${{ toJSON(github) }}"
